from time import sleep


# wait 2 seconds, then raise an exception
print("testfile_2 has started!")
sleep(5)
raise Exception ("I also fell over")
